diary/urls.py
from django.urls import path

from . import views

app_name = 'diary'
urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
<<<<<<< HEAD
    path('inquiry/',views.InquiryView.as_view(),name="inquiry"),
    path('sugainquiry/',views.SugaInquiryView.as_view(),name="sugainquiry"),
    path('diary-list/', views.DiaryListView.as_view(), name="diary-list"),
    path('diary-detail/<int:pk>/', views.DiaryDetailView.as_view(), name="diary_detail"),
    path('diary-create/', views.DiaryCreateView.as_view(), name="diary_create"),

=======
    path('inquiry',views.InquiryView.as_view(),name="inquiry"),
    path('diary-list', views.DiaryListView.as_view(), name="diary-list"),
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052
    path('suga',views.SugaView.as_view(), name="yuki")

]

private_diary/urls.py
from django.contrib import admin
<<<<<<< HEAD
from django.urls import path,include
from django.contrib.staticfiles.urls import static

=======
from django.urls import path
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052


from django.urls import path,include

from django.contrib import admin
from django.urls import path,include

<<<<<<< HEAD
from . import settings_common,settings_dev

=======
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),

<<<<<<< HEAD
    path('accounts/', include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるように設定
urlpatterns += static(settings_common.MEDIA_URL,document_root = settings_dev.MEDIA_ROOT)
=======
    # path('accounts/', include('allauth.urls')),
]
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052

diary/models.py
from django.db import models

# Create your models here.
class Diary(models.Model):

<<<<<<< HEAD
    # user = models.ForeignKey(CustomUser,verbose_name='ユーザー',on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル',max_length=40)
    content = models.CharField(verbose_name='本文',blank=True,null=True)
    created_at = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)
    # updateed_at = models.DateTimeField(verbose_name='更新日時',auto_now=True)

    # photo1 = models.ImageField(verbose_name='写真1',blank=True,null=True)
    # photo2 = models.ImageField(verbose_name='写真2',blank=True,null=True)
    # photo3 = models.ImageField(verbose_name='写真3',blank=True,null=True)

=======
    title = models.CharField(verbose_name='タイトル',max_length=40)
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052
    class Meta:
        verbose_name_plural = 'Diary'

    def __str__(self):
<<<<<<< HEAD
        return self.title

=======
        return self.title
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052

diary/forms.py
import os

from django import forms
from django.core.mail import EmailMessage
<<<<<<< HEAD
from .models import Diary
=======
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052

class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前',max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル',max_length=30)
    message = forms.CharField(label='メッセージ',widget=forms.Textarea)
    dream = forms.CharField(label='夢っす', widget=forms.Textarea)


    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してくださいね。'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

        self.fields['dream'].widget.attrs['class'] = 'form-control'
        self.fields['dream'].widget.attrs['placeholder'] = 'あなたの夢をここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問合わせ{}'.format(title)
        message = 'お問合わせよ:{0}\nメールアドレスだよ：{1}\nメッセージだよ：{2}'.format(name,email,message)

        from_email = os.environ.get('FROM_EMAIL')
        to_list = [
            os.environ.get('FROM_EMAIL')
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject= subject,body=message,from_email=from_email,to=to_list,cc=cc_list)
<<<<<<< HEAD
        message.send()


class SugaForm(forms.Form):
    name = forms.CharField(label='やる気',max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='棒読み感',max_length=30)
    message = forms.CharField(label='不思議さ',widget=forms.Textarea)
    dream = forms.CharField(label='度胸', widget=forms.Textarea)


    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してくださいね。'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

        self.fields['dream'].widget.attrs['class'] = 'form-control'
        self.fields['dream'].widget.attrs['placeholder'] = 'あなたの夢をここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問合わせ{}'.format(title)
        message = 'お問合わせよ:{0}\nメールアドレスだよ：{1}\nメッセージだよ：{2}'.format(name,email,message)

        from_email = os.environ.get('FROM_EMAIL')
        to_list = [
            os.environ.get('FROM_EMAIL')
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject= subject,body=message,from_email=from_email,to=to_list,cc=cc_list)
        message.send()



class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        # fields = ('title','content','photo1','photo2','photo3')
        fields = ('title','content')
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'



=======
        message.send()
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052

diary/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import  messages
from .forms import InquiryForm
<<<<<<< HEAD
from .forms import DiaryCreateForm
from .forms import SugaForm
from .models import Diary
=======
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052

import logging

logger = logging.getLogger(__name__)

<<<<<<< HEAD
=======

>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052
class IndexView(generic.TemplateView):
    template_name = "index.html"

# class InquiryView((generic.TemplateView):):
class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('diary:inquiry')

    def form_valid(self, form):
        form.send_email()
        logger.info('inquiry sent by {}'.format(form.cleaned_data['name']) )
        messages.success(self.request,'お問い合わせが完了しました。')
        return super().form_valid(form)

<<<<<<< HEAD
class SugaInquiryView(generic.FormView):
    template_name = "suga_inquiry.html"
    form_class = SugaForm
    success_url = reverse_lazy('diary:sugainquiry')

    def form_valid(self, form):
        form.send_email()
        logger.info('inquiry sent by {}'.format(form.cleaned_data['name']) )
        messages.success(self.request,'お問い合わせが完了しました。')
        return super().form_valid(form)


class SugaView(generic.TemplateView):
    template_name = "suga.html"

class DiaryListView(generic.ListView):
    model = Diary
    template_name = "diary_list.html"
    paginnate_by = 2

    def get_queryset(self):
        # diaries = Diary.objects.filter(user = self.request.user).order_by('created_at')
        diaries = Diary.objects.order_by('created_at')
        return diaries

class DiaryDetailView(generic.DetailView):
    model = Diary
    template_name = 'diary_detail.html'
    pk_url_kwarg = 'id'

class DiaryCreateView(generic.CreateView):
    model = Diary
    template_name = 'diary_create.html'
    form_class = DiaryCreateForm
    success_url = reverse_lazy('diary:diary-list')
=======
class SugaView(generic.TemplateView):
    template_name = "suga.html"

class DiaryListView(generic.TemplateView):
    # model = Diary
    template_name = "diary_list.html"
    # paginnate_by = 2

    def get_queryset(self):
        diaries = Diary.objects.filter(user = self.request.user).order_by('created_at')
        return diaries

>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052

diary/templates/base.html
{% load static %}

<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet" />

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
  </head>

  <body>
    <div id="wrapper">
      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
          <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'diary:inquiry' %}">INQUIRY</a>
              </li>

              <li class="nav-item">
                <a class="nav-link {% block active_suga %}{% endblock %}" href="{% url 'diary:yuki' %}">SUGA</a>
              </li>

              <li class="nav-item">
                <a class="nav-link {% block active_diary-list %}{% endblock %}" href="{% url 'diary:diary-list' %}">DIARY-LIST</a>
              </li>
<<<<<<< HEAD

             <li class="nav-item">
                 <a class="nav-link {% block active_sugainquiry %}{% endblock %}" href="{% url 'diary:sugainquiry' %}">SUGA INQUIRY</a>
             </li>
=======
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052
            </ul>
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link" href="#">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Log In</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {% block header%}{% endblock %}
    　{% if messages %}
    	<div class="container my-div-style">
            <div class="row">
                {% for message in messages %}
                    <ul class="messages" style="list-style: none">
                        <li {% if message.tags %}class="{{message.tags}}" {% endif %}>{{message}}</li>
                    </ul>
                {% endfor %}
            </div>
        </div>
      {% endif %}

      {% block contents%}{% endblock %}

      <!-- Footer -->
      <footer class="py-5 bg-black">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Private Dairy 2021</p></div>
      </footer>

      <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    </div>
  </body>
</html>

diary/templates/diary_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記作成 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">作成</button>
        </form>
    </div>
</div>
{% endblock %}

diary/templates/diary_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記削除 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            <p>本当に削除しますか？</p>
            <button class="btn btn-primary mt-5" type="submit">削除</button>
            <a class="btn btn-secondary mt-5 ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

diary/templates/diary_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記詳細 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}


{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <div class="col-3">
            <strong>タイトル</strong>
        </div>
        <div class="col-9">
            {{ object.title }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>本文</strong>
        </div>
        <div class="col-9">
            {{ object.content|linebreaksbr }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>写真</strong>
        </div>
        <div class="col-3">
            {% if object.photo1 %}
            <img src="{{ object.photo1.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <div class="col-3">
            {% if object.photo2 %}
            <img src="{{ object.photo2.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <div class="col-3">
            {% if object.photo3 %}
            <img src="{{ object.photo3.url }}" width="200" height="200"/>
            {% endif %}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>作成日時</strong>
        </div>
        <div class="col-9">
            {{ object.created_at }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>更新日時</strong>
        </div>
        <div class="col-9">
            {{ object.updated_at }}
        </div>
    </div>

    <a class="btn btn-success mt-5 mb-3" href="{% url 'diary:diary_update' object.pk %}">編集</a>
    <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'diary:diary_delete' object.pk %}">削除</a>
</div>
{% endblock %}

diary/templates/diary_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記一覧 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<<<<<<< HEAD
{#<div class="container px-4 px-lg-5 my-div-style">#}
{#    <div class="row gx-4 gx-lg-5 justify-content-center">#}
{#        <div class="col-md-10 col-lg-8 col-xl-7">#}
{#            <div class="d-flex justify-content-end mb-4">#}
{#                <a class="btn btn-primary float-right" href="{% url 'diary:diary_create' %}">新規作成</a>#}
{#            </div>#}
{#            {% for diary in diary_list %}#}
{#            <div class="post-preview">#}
{#                <a href="{% url 'diary:diary_detail' diary.pk %}">#}
{#                    <h2 class="post-title">#}
{#                        {{ diary.title }}#}
{#                    </h2>#}
{#                    <h3 class="post-subtitle">#}
{#                        {{ diary.content|truncatechars:20 }}#}
{#                    </h3>#}
{#                </a>#}
{#                <p class="post-meta">{{ diary.created_at }}</p>#}
{#            </div>#}
{#            <hr class="my-4">#}
{#            {% empty %}#}
{#            <p>日記がありません。</p>#}
{#            {% endfor %}#}
{##}
{#            <!-- ページネーション処理 -->#}
{#            {% if is_paginated %}#}
{#            <ul class="pagination">#}
{#                <!-- 前ページへのリンク -->#}
{#                {% if page_obj.has_previous %}#}
{#                <li class="page-item">#}
{#                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">#}
{#                        <span aria-hidden="true">&laquo;</span>#}
{#                    </a>#}
{#                </li>#}
{#                {% endif %}#}
{##}
{#                <!-- ページ数表示 -->#}
{#                {% for page_num in page_obj.paginator.page_range %}#}
{#                {% if page_obj.number == page_num %}#}
{#                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>#}
{#                {% else %}#}
{#                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>#}
{#                {% endif %}#}
{#                {% endfor %}#}
{##}
{#                <!-- 次ページへのリンク -->#}
{#                {% if page_obj.has_next %}#}
{#                <li class="page-item">#}
{#                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">#}
{#                        <span aria-hidden="true">&raquo;</span>#}
{#                    </a>#}
{#                </li>#}
{#                {% endif %}#}
{#            </ul>#}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}
{#</div>#}
=======
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary float-right" href="{% url 'diary:diary_create' %}">新規作成</a>
            </div>
            {% for diary in diary_list %}
            <div class="post-preview">
                <a href="{% url 'diary:diary_detail' diary.pk %}">
                    <h2 class="post-title">
                        {{ diary.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ diary.content|truncatechars:20 }}
                    </h3>
                </a>
                <p class="post-meta">{{ diary.created_at }}</p>
            </div>
            <hr class="my-4">
            {% empty %}
            <p>日記がありません。</p>
            {% endfor %}

            <!-- ページネーション処理 -->
            {% if is_paginated %}
            <ul class="pagination">
                <!-- 前ページへのリンク -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                <!-- ページ数表示 -->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
                {% endfor %}

                <!-- 次ページへのリンク -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052
{% endblock %}

diary/templates/diary_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記編集 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">更新</button>
            <a class="btn btn-secondary ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

diary/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Web上にお前専用の日記ページを保存できるサービス | Private Diary{% endblock %}

{% block header%}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">Private Diary</h1>
      <h2 class="masthead-subheading mb-0">あなた専用の日記保存サービス</h2>
      <a href="#" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'assets/img/01.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Web Diary</h2>
          <p>Web上で作成/編集/削除ができる日記</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'assets/img/02.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">Save Your Diary</h2>
          <p>あなたの日記をWebに保存</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'assets/img/03.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Membership System</h2>
          <p>会員制のWeb日記サービス</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

diary/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ | Private Diary{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style">
        <form method="post">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for field in form %}
            <div class="mb-4 col-8">
                <label for="{{ field.id_for_label }}" class="form-label">
                    <strong>{{ field.label_tag }}</strong>
                </label>
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}

            <button class="btn btn-primary" type="submit">送信</button>
        </form>
    </div>
</div>
{% endblock %}

diary/templates/suga.html
{% extends 'base.html' %}
{% load static %}

{% block active_suga %}active{% endblock %}
{% block title %}Suga専用の日記ページ{% endblock %}


{% block header%}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">Private Diary</h1>
<<<<<<< HEAD
      <h2 class="masthead-subheading mb-0">SUGA YUKI専用の日記保存サービス</h2>
=======
      <h2 class="masthead-subheading mb-0">SUGA専用の日記保存サービス</h2>
>>>>>>> ce8f1603a7b4955e9d1ec2996b6376a5e5e36052
      <a href="#" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

diary/templates/suga_inquiry.html
{% extends 'base.html' %}

{% block title %}SUGAお問い合わせ | Private Diary{% endblock %}

{% block active_sugainquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style">
        <form method="post">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for field in form %}
            <div class="mb-4 col-8">
                <label for="{{ field.id_for_label }}" class="form-label">
                    <strong>{{ field.label_tag }}</strong>
                </label>
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}

            <button class="btn btn-primary" type="submit">送信</button>
        </form>
    </div>
</div>
{% endblock %}